### ISSUE TITLE
Define required token permissions

### ISSUE THREAD

**Issue by djhoese** [spyder-ide/loghub#101]
I've been using a password for loghub for a while now but when I used it today I was warned by GitHub that password access is going away for this API. I created a token and specified it with the `--token` flag but was still prompted for a password by loghub. I assume this was because the token wasn't given enough permission on GitHub. I wasn't sure what permissions were needed so I only selected a few options.

Would it be possible to document what permissions are needed for loghub to fully work?

**Comment by djhoese** [comment]
:man_facepalming: I was still passing `-u` flag. Nevermind.

**Comment by ccordoba12** [comment]
No problem, and glad to know you keep using loghub!

**Comment by goanpeca** [comment]
@ccordoba12 should we disable user and password for good for this new release?
