### ISSUE TITLE
Support hidden password

### ISSUE THREAD

**Issue by fpliger** [spyder-ide/loghub#11]
ATM user needs to specify their password for private repos using the `-p` argument when calling the script. This is not option for security reasons since user password is easily exposed (when working in public spaces, in system history, etc...). It'd be beneficial to ask the user with python `getpass` module.

**Comment by fpliger** [comment]
Would it be ok to ask for a password when `-u` is specified but `-p` is not? or there **is** a use case when users need to specify their username but don't need password?

**Comment by ccordoba12** [comment]
> or there is a use case when users need to specify their username but don't need password?

I don't think there is, so yes, passowords must be asked when `-u` is passed as an option.
