### ISSUE TITLE
Add PR link / commit link inside issue

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/loghub#63]
`Issue #45 - Some text (PR#52 or jaksdads)`

**Comment by goanpeca** [comment]
@fpliger, @ccordoba12 this is how it would look with extra links for both issues and PRs, comments? suggestions?

## Version 0.2 (2017-02-01)

### Issues Closed

* [Issue 64](https://github.com/spyder-ide/loghub/issues/64) - Create release for v0.2
* [Issue 57](https://github.com/spyder-ide/loghub/issues/57) - Allow Enable/Disable of PR output ([PR 65](https://github.com/spyder-ide/loghub/pull/65))
* [Issue 56](https://github.com/spyder-ide/loghub/issues/56) - Fix output for grouped labels if no items on that group ([PR 58](https://github.com/spyder-ide/loghub/pull/58))
* [Issue 55](https://github.com/spyder-ide/loghub/issues/55) - Fix date on generation based on milestone ([PR 58](https://github.com/spyder-ide/loghub/pull/58))
* [Issue 53](https://github.com/spyder-ide/loghub/issues/53) - Normalize CI files using requirements.txt ([PR 60](https://github.com/spyder-ide/loghub/pull/60))
* [Issue 52](https://github.com/spyder-ide/loghub/issues/52) - Update README to use full commands ([PR 58](https://github.com/spyder-ide/loghub/pull/58))
* [Issue 47](https://github.com/spyder-ide/loghub/issues/47) - Update Appveyor Badge for new username spyder-ide ([PR 48](https://github.com/spyder-ide/loghub/pull/48))
* [Issue 46](https://github.com/spyder-ide/loghub/issues/46) - Create labels automagically on github based on template ([PR 59](https://github.com/spyder-ide/loghub/pull/59))
* [Issue 42](https://github.com/spyder-ide/loghub/issues/42) - Generate all changelog based on milestones
* [Issue 41](https://github.com/spyder-ide/loghub/issues/41) - Add default template for release with issue label grouping ([PR 43](https://github.com/spyder-ide/loghub/pull/43))
* [Issue 40](https://github.com/spyder-ide/loghub/issues/40) - Provide available milestones to user when provided not found ([PR 44](https://github.com/spyder-ide/loghub/pull/44))
* [Issue 39](https://github.com/spyder-ide/loghub/issues/39) - Add checkignore to quantified code
* [Issue 30](https://github.com/spyder-ide/loghub/issues/30) - Add label groupings ([PR 34](https://github.com/spyder-ide/loghub/pull/34))
* [Issue 28](https://github.com/spyder-ide/loghub/issues/28) - Generate all changelog based on tags ([PR 61](https://github.com/spyder-ide/loghub/pull/61))
* [Issue 27](https://github.com/spyder-ide/loghub/issues/27) - Generate all changelog based on milestones ([PR 61](https://github.com/spyder-ide/loghub/pull/61))
* [Issue 23](https://github.com/spyder-ide/loghub/issues/23) - Update Readme with new CLI parameters ([PR 36](https://github.com/spyder-ide/loghub/pull/36))
* [Issue 21](https://github.com/spyder-ide/loghub/issues/21) - Add branch parameter to select PRs to display based on the merging branch ([PR 32](https://github.com/spyder-ide/loghub/pull/32))
* [Issue 16](https://github.com/spyder-ide/loghub/issues/16) - Better authorization handling  ([PR 44](https://github.com/spyder-ide/loghub/pull/44))
* [Issue 15](https://github.com/spyder-ide/loghub/issues/15) - Since tag not working properly ([PR 13](https://github.com/spyder-ide/loghub/pull/13))
* [Issue 11](https://github.com/spyder-ide/loghub/issues/11) - Support hidden password ([PR 14](https://github.com/spyder-ide/loghub/pull/14))
* [Issue 10](https://github.com/spyder-ide/loghub/issues/10) - Support custom line formats [templates] ([PR 20](https://github.com/spyder-ide/loghub/pull/20))
* [Issue 8](https://github.com/spyder-ide/loghub/issues/8) - Support "all issues"  ([PR 19](https://github.com/spyder-ide/loghub/pull/19))
* [Issue 4](https://github.com/spyder-ide/loghub/issues/4) - Expose labels for additional filtering ([PR 17](https://github.com/spyder-ide/loghub/pull/17))
* [Issue 3](https://github.com/spyder-ide/loghub/issues/3) - Add access token interface ([PR 18](https://github.com/spyder-ide/loghub/pull/18))
* [Issue 2](https://github.com/spyder-ide/loghub/issues/2) - Add some basic tests ([PR 29](https://github.com/spyder-ide/loghub/pull/29))

In this release 25 issues were closed.

### Pull Requests Merged

* [PR 65](https://github.com/spyder-ide/loghub/pull/65) - PR: Add support for no-prs on output ([57](https://github.com/spyder-ide/loghub/issues/57))
* [PR 61](https://github.com/spyder-ide/loghub/pull/61) - PR: Add batch mode for all tags for all milestones ([28](https://github.com/spyder-ide/loghub/issues/28), [27](https://github.com/spyder-ide/loghub/issues/27))
* [PR 60](https://github.com/spyder-ide/loghub/pull/60) - PR: Add requirements file and update CI process ([53](https://github.com/spyder-ide/loghub/issues/53))
* [PR 59](https://github.com/spyder-ide/loghub/pull/59) - PR: Add a label creator utility ([46](https://github.com/spyder-ide/loghub/issues/46))
* [PR 58](https://github.com/spyder-ide/loghub/pull/58) - PR: Refactor code and simplify group handling ([56](https://github.com/spyder-ide/loghub/issues/56), [55](https://github.com/spyder-ide/loghub/issues/55), [52](https://github.com/spyder-ide/loghub/issues/52))
* [PR 54](https://github.com/spyder-ide/loghub/pull/54) - PR: Remove versioneer
* [PR 51](https://github.com/spyder-ide/loghub/pull/51) - PR: Update ignore file to ignore versioneer files
* [PR 50](https://github.com/spyder-ide/loghub/pull/50) - PR: Add versioneer for version string control based on git tags not on manual editing ([49](https://github.com/spyder-ide/loghub/issues/49))
* [PR 48](https://github.com/spyder-ide/loghub/pull/48) - PR: Update AppVeyor badge because of move to org account ([47](https://github.com/spyder-ide/loghub/issues/47))
* [PR 45](https://github.com/spyder-ide/loghub/pull/45) - PR: Break into smaller funcs
* [PR 44](https://github.com/spyder-ide/loghub/pull/44) - PR: Improve error handling ([40](https://github.com/spyder-ide/loghub/issues/40), [16](https://github.com/spyder-ide/loghub/issues/16))
* [PR 43](https://github.com/spyder-ide/loghub/pull/43) - PR: Add template for release grouped issue labels ([41](https://github.com/spyder-ide/loghub/issues/41))
* [PR 36](https://github.com/spyder-ide/loghub/pull/36) - PR: Update readme with latest CLI commands ([23](https://github.com/spyder-ide/loghub/issues/23))
* [PR 34](https://github.com/spyder-ide/loghub/pull/34) - PR: Add label grouping for issues  ([30](https://github.com/spyder-ide/loghub/issues/30))
* [PR 32](https://github.com/spyder-ide/loghub/pull/32) - PR: Feature/branch ([21](https://github.com/spyder-ide/loghub/issues/21))
* [PR 31](https://github.com/spyder-ide/loghub/pull/31) - PR: Refactor code
* [PR 29](https://github.com/spyder-ide/loghub/pull/29) - PR: Maintenance/tests ([2](https://github.com/spyder-ide/loghub/issues/2))
* [PR 20](https://github.com/spyder-ide/loghub/pull/20) - PR: Feature/templates ([10](https://github.com/spyder-ide/loghub/issues/10))
* [PR 19](https://github.com/spyder-ide/loghub/pull/19) - PR: Add support for all issues when no tag or no milestone is provided ([8](https://github.com/spyder-ide/loghub/issues/8))
* [PR 18](https://github.com/spyder-ide/loghub/pull/18) - PR: Add support for github tokens ([3](https://github.com/spyder-ide/loghub/issues/3))
* [PR 17](https://github.com/spyder-ide/loghub/pull/17) - PR: Add regex label filtering for issues and prs ([4](https://github.com/spyder-ide/loghub/issues/4))
* [PR 14](https://github.com/spyder-ide/loghub/pull/14) - add password prompt when user is specified and password is blank ([11](https://github.com/spyder-ide/loghub/issues/11))
* [PR 13](https://github.com/spyder-ide/loghub/pull/13) - PR: Fix bug on since keyword returning incorrect issues ([15](https://github.com/spyder-ide/loghub/issues/15))
* [PR 12](https://github.com/spyder-ide/loghub/pull/12) - Don't test macOS in Travis
* [PR 9](https://github.com/spyder-ide/loghub/pull/9) - Don't show "Issues" or "Pull requests" sections if there are no issues or PRs to show
* [PR 7](https://github.com/spyder-ide/loghub/pull/7) - Fix contents of temporary file
* [PR 6](https://github.com/spyder-ide/loghub/pull/6) - Remove extra empty lines
* [PR 5](https://github.com/spyder-ide/loghub/pull/5) - Fix PR_SHORT formatting.
* [PR 1](https://github.com/spyder-ide/loghub/pull/1) - Several fixes

In this release 29 pull requests were closed.



## Version 1.5 (2017/03/07)

### Issues Closed

#### Features 

* [Issue 916](https://github.com/continuumio/navigator/issues/916) - Add project tab  ([PR 930](https://github.com/ContinuumIO/navigator/pull/930))

#### Enhancements

* [Issue 911](https://github.com/continuumio/navigator/issues/911) - Be more aggressive with updates on startup ([PR 931](https://github.com/ContinuumIO/navigator/pull/931))

#### Bugs fixed

* [Issue 951](https://github.com/continuumio/navigator/issues/951) - Import New Project \\ In import popup, help icon is not working.  ([PR 955](https://github.com/ContinuumIO/navigator/pull/955))
* [Issue 942](https://github.com/continuumio/navigator/issues/942) - Upgrade navigator change the version 1.4.3 to 1.5.dev0 . ([PR 955](https://github.com/ContinuumIO/navigator/pull/955))
* [Issue 932](https://github.com/continuumio/navigator/issues/932) - Remove hardcoded fusion check ([PR 935](https://github.com/ContinuumIO/navigator/pull/935))
* [Issue 914](https://github.com/continuumio/navigator/issues/914) - Notebooks open in different directories for home and env ([PR 920](https://github.com/ContinuumIO/navigator/pull/920))
* [Issue 910](https://github.com/continuumio/navigator/issues/910) - Anaconda New Install - Launcher not working ([PR 921](https://github.com/ContinuumIO/navigator/pull/921))

In this release 7 issues were closed.

### Pull Requests Merged

* [PR 955](https://github.com/continuumio/navigator/pull/955) - PR: Fix popup information on spec project import dialog ([951](https://github.com/ContinuumIO/navigator/issues/951), [942](https://github.com/ContinuumIO/navigator/issues/942))
* [PR 954](https://github.com/continuumio/navigator/pull/954) - PR: Add entry points for windows fix ([941](https://github.com/ContinuumIO/navigator/issues/941))
* [PR 940](https://github.com/continuumio/navigator/pull/940) - PR: Add jpg images to package data to prevent errors ([929](https://github.com/ContinuumIO/navigator/issues/929))
* [PR 938](https://github.com/continuumio/navigator/pull/938) - PR: Release candidate fixes
* [PR 935](https://github.com/continuumio/navigator/pull/935) - PR: Disable hard coded checks for fusion and rstudio ([932](https://github.com/ContinuumIO/navigator/issues/932), [912](https://github.com/ContinuumIO/navigator/issues/912), [909](https://github.com/ContinuumIO/navigator/issues/909))
* [PR 933](https://github.com/continuumio/navigator/pull/933) - PR: Use CI with 2.7 3.5 and 3.6 only ([934](https://github.com/ContinuumIO/navigator/issues/934))
* [PR 931](https://github.com/continuumio/navigator/pull/931) - PR: Update the upgrade dialog and display ([911](https://github.com/ContinuumIO/navigator/issues/911))
* [PR 930](https://github.com/continuumio/navigator/pull/930) - PR: Feature/projects ([916](https://github.com/ContinuumIO/navigator/issues/916))
* [PR 921](https://github.com/continuumio/navigator/pull/921) - PR: Add quotes if command includes spaces ([910](https://github.com/ContinuumIO/navigator/issues/910))
* [PR 920](https://github.com/continuumio/navigator/pull/920) - PR: Open notebooks on home tab in the same location (home dir) ([914](https://github.com/ContinuumIO/navigator/issues/914))

In this release 10 pull requests were closed.

**Comment by ccordoba12** [comment]
I like it!! It looks really nice :-)

**Comment by fpliger** [comment]
Sweet!
