### ISSUE TITLE
Support "all issues" 

### ISSUE THREAD

**Issue by fpliger** [spyder-ide/loghub#8]
It'd be nice to be able to generate a changelog since the beginning without having to specify either `ut` or `st` for first time generation of projects that didn't start with a clear tagging/release policy from the start or just want to put all in the changelog

**Comment by ccordoba12** [comment]
@goanpeca?

**Comment by goanpeca** [comment]
Hi @fpliger sure, I think I can make it work

**Comment by fpliger** [comment]
(I'm just listing some issues that would help to adopt loghub internally... I should have some bandwith to contribute on these issues over the long weekend)

**Comment by goanpeca** [comment]
Sure, anything that might help to make it more general is welcome :-). Feel free to open more issues

**Comment by ccordoba12** [comment]
Thanks @fpliger, it'd be really nice to see other Continuum projects to adopt this little projects of ours :-)

**Comment by fpliger** [comment]
🙌
