### ISSUE TITLE
Add option to disable related issues and PRs

### ISSUE THREAD

**Issue by djhoese** [spyder-ide/loghub#93]
Sometimes relationships between PRs and issues can get complicated or a user may not want to list the related PRs/issues next to the entry for an issue/PR. I'd like to propose a command line flag to simply turn off this additional information. Essentially turning off the call to `filter_issues_fixed_by_prs(filtered_issues, filtered_prs)` in the `formatter.py` code.

It could alternatively be passed to the template so it could decide not to show the relationships.

**Comment by djhoese** [comment]
Additionally, the line I quoted above looks like it has a bug where `filtered_issues` should actually be `new_filtered_issues`, right?

**Comment by ccordoba12** [comment]
I agree with this request. Please implement it.

**Comment by djhoese** [comment]
@ccordoba12 I'll try to get to it after my other PR is finished. I looked at the possible bug I mentioned above and maybe this is desired: https://github.com/spyder-ide/loghub/blob/master/loghub/core/formatter.py#L263

Doing it the way it instead of using `new_filtered_issues` means that even issues/PRs that aren't in the groups will get associated with issues/PRs that are in groups.

**Comment by goanpeca** [comment]
@djhoese still using the project? I am cleaning the dust out of loghub so your input is highly appreciated :-) 

I just added support for Zenhub Releases!

**Comment by djhoese** [comment]
I am using it, but just decided not to use this feature discussed here.

**Comment by goanpeca** [comment]
Could you test the PR I just created? it should fix the issues you mentioned!
